### ISSUE TITLE
Errors during compilation (magento 2.1.3)

### ISSUE THREAD

**Issue by Fouad90** [klevu/klevu-smart-search-M2#10]
Total Errors Count: 1
Errors during compilation:
	Klevu\Search\Controller\Index\Runexternaly
		Incorrect dependency in class Klevu\Search\Controller\Index\Runexternaly in /htdocs/vendor/klevu/module-productsearch/Controller/Index/Runexternaly.php
\Magento\Framework\Message\ManagerInterface already exists in context object
Total Errors Count: 1

Removing:
\Magento\Framework\Message\ManagerInterface $messageManager 
From the constructor in Controller/Index/Runexternaly.php solved the problem for me.

**Comment by claudiusararu** [comment]
@Fouad90 recommendation worked. Thanks!

**Comment by klevu** [comment]
No longer valid, fixed in new version
