### ISSUE TITLE
Error after requied in magento 2.1.3

### ISSUE THREAD

**Issue by thanhhuykhtn** [klevu/klevu-smart-search-M2#11]
There has been an error processing your request  
Exception printing is disabled by default for security reasons.
Error log record number: 761783755689

in report file :
a:4:{i:0;s:346:"Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
Klevu_Addtocart data: current version - none, required version - 2.1.12
Klevu_Search data: current version - none, required version - 2.1.12
Klevu_Content data: current version - none, required version - 2.1.12";i:1;s:888:"#0 C:\wamp64\www\shopmagento\vendor\magento\framework\Interception\Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#1 C:\wamp64\www\shopmagento\var\generation\Magento\Framework\App\FrontController\Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#2 C:\wamp64\www\shopmagento\vendor\magento\framework\App\Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#3 C:\wamp64\www\shopmagento\vendor\magento\framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch()
#4 C:\wamp64\www\shopmagento\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#5 {main}";s:3:"url";s:106:"/shopmagento/admin/admin/index/index/key/67e17304b39d1ca82635d8f75d5777009197310dc359ec234f5250aa15df1e90/";s:11:"script_name";s:22:"/shopmagento/index.php";}

Please help me. thanks

**Comment by klevu** [comment]
No longer valid, fixed in new version
