### ISSUE TITLE
"YOU MAY LIKE" Product Images Disappeared

### ISSUE THREAD

**Issue by orhantghp** [klevu/klevu-smart-search-M2#13]
After updating to version 2.1.30 the product images on "You may like" section of search results are not showing giving me 404 error.

I've examined the URL its trying to fetch the images from and it contains the directory "needtochange/". The JS function located at file "vendor/klevu/module-productsearch/view/frontend/templates/klevu/search/form_js.phtml" lines 82 to 96 is not being called, this function replaces "needtochange/" with "pub/" for actual search results found but not for the "You may like" section.

**Comment by klevu** [comment]
Thank you for the report.
We will correct the issues asap.
