### ISSUE TITLE
Question to devs - related to one magento bug

### ISSUE THREAD

**Issue by anatolij-p** [klevu/klevu-smart-search-M2#15]
We are testing your module for Product Listing Page (PLP).
I have some questions for you:

* as far as i can tell all the data is coming from klevu api - no magento db is used for filtering at all
* therefore since no data is coming from magento this issue should never appear when using klevu for PLP page (https://github.com/magento/magento2/issues/15545#issuecomment-522312589)

Am I getting this correctly?

**Comment by tejasklevu** [comment]
Hi there. Would it be possible for you to share the details on support@klevu.com with more details on the issue you are facing? We will help you further. thanks

**Comment by anatolij-p** [comment]
I would prefer to talk directly to module developer.

There is no issue, I just need confirmation from developers about how this module operates.

**Comment by tejasklevu** [comment]
Hi. I am also one of the Magento developers at Klevu. Your question depends on the layout you are using with Klevu. Klevu provides, two layout option, the one is "Klevu Based Template" layout where the Klevu is responsible for rendering the search landing page e.g. https://m2.klevu.com/search/?q=tee
The second is "Preserve Your theme Layout" option where the layout is rendered from Magento theme only. Klevu only calls one API to the backend and fetched the relevant product IDs. this product IDs are used for relevancy purpose on the site.
As on the second option, the Magento is responsible for rendering the results and layered navigation as well, KLevu does not have control over it. Can you please check it at your end?
Hope this answer is helpful.

**Comment by anatolij-p** [comment]
OK, we are using Klevu based templates.

And if we use that template ALL the data for search/plp will be coming from Klevu.
That means that the issue in that link from github would be impossible to happen if we are using "Klevu Based Template". Did I got that correctly?

**Comment by anatolij-p** [comment]
I just need confirmation that when 'Klevu templates' are being used (plp, search pages) there is NO usage of Magento database. If you can confirm, thats all i need.

**Comment by tejasklevu** [comment]
Hi. yes, that is true. if the 'Klevu templates' is used, there is no usage of the Magento Databases on PLP and search landing page. But please note, while syncing data to the Klevu backend, module uses the Magento functions to fetch the data.

**Comment by anatolij-p** [comment]
Excellent, thanks for answer that is all i needed to know.

**Comment by tejasklevu** [comment]
thanks for the kind words :)  just want to share that we will be closing this portal. If you have any queries, feel free to reach us out at support@klevu.com
