### ISSUE TITLE
Search Result Page Settings issue

### ISSUE THREAD

**Issue by elioermini** [klevu/klevu-smart-search-M2#2]
Search Result Page Settings only display the Klevu option, tested on Magento 2.1 with luma theme.

**Comment by elioermini** [comment]
Looks like the options are commented out in Klevu\Search\Model\System\Config\Source\Landingoptions

**Comment by klevu** [comment]
Hi there, we have the preserve layout option available in M1 and we are still testing out our changes for the preserve layout option for M2. We'll uncomment the preserve layout option when the changes are applied.
