### ISSUE TITLE
Incorrect module structure

### ISSUE THREAD

**Issue by AndreKlang** [klevu/klevu-smart-search-M2#6]
Hi,

This repo has an incorrect structure according to Magento's guidelines, and can therefore not be installed or managed with composer.

To my knowledge there is only two options to fix this:
1. Merge your three modules to one
2. Split your repo into three separate repos, containing one module each.

I'd recommend you go with option 2, and actually that you have one fourth repo (this one) that acts as a meta package, requiring the correct version of the other packages.

If you still want to be able to offer a "download this zip-file" option, you can easily add a travis job to package all the repos together.

**Comment by AndreKlang** [comment]
Actually, It seams that my statement that it "can not be installed with composer" was a bit premature. The three modules actually does install and seams to be working.

It still violates the guidelines though, so it is a real possibility that there will be other issues down the line.

**Comment by klevu** [comment]
Hi Andre,

Apology for the delay. The plugin was updated on the git hub and It now has
subpackages and a meta package. Please, can you have a look?

Regards,
Niraj



ᐧ

**Comment by klevu** [comment]
Hi Andre and Maura,

The plugin was updated on the Github as per your recommendations of how it
should be organized. We see that many customers have already installed it
without any issues.

@Andre:

About your comment on moving Klevu Search configurations under the Catalog
section, unless it is mandatory, we would like to keep it as it is, at
least for now, as our customers have got used to with it and all our
documentation published publicly refer to this way of using Klevu. I hope
you understand!

Please, can you let us know the next steps?

Regards,
Niraj
CTO, Klevu Search
