### ISSUE TITLE
Pollution in admin

### ISSUE THREAD

**Issue by AndreKlang** [klevu/klevu-smart-search-M2#7]
Hi,

In admin under configuration you add a new tab called "Klevu" containing only one section. My question is why?

This was also a pain in M1-modules, every single vendor added their own tabs and menu items to admin. Fine if you have only one or two third party modules, it's an issue if you have 10-20 modules.

My suggestion is to move the "Search Configuration"-section into the "Catalog"-tab and rename it to "Klevu Search Configuration"

**Comment by klevu** [comment]
Hi Andre,

Thank you for your initial feedback.

You're right, at the moment there is only one item "Search configurations"
under Klevu. However, soon we will be adding another item (i.e. Help
Center). Do you still think we should move it under catalog?

Regards,
Niraj
ᐧ

**Comment by AndreKlang** [comment]
Hi,

It depends what "Help Center" is. If it is a link you your help-center for merchants, I think that it is better suited inside the section for "Search configurations", since that is the place the merchant actually need help.

If it however actually contain configuration for a Help Center, then I'd place it under the "General"-tab.

Creating a new tab should be considered an absolute last resort.

**Comment by klevu** [comment]
Hi Andre,

We are working on these issues reported by you and we will get back to you
on the same latest by tomorrow.

Regards,
Niraj
ᐧ
